args = commandArgs(trailingOnly=TRUE)

if (length(args)<10) {
  stop("Incorrect number of arguments supplied", call.=FALSE)
} else {
	d <- policy_simulation(
		saveCSV=TRUE,
		xvars=c("widowed", "divorced", "separated", "nevermarried", "female", 
			  'age_cat', "ltHS", "someCol", "BA", "GradSch", "black", 
			  "other", "asian",'native', "hisp","nochildren",'faminc_cat','coveligd'),
		base_bene_level=args[0],
		impute_method=args[1],
		makelog = args[2],
		sample_prop=args[3],
		state=args[4],
		FEDGOV=args[],
		STATEGOV=args[],
		LOCALGOV=args[],
		SELFEMP=args[5],
		place_of_work = args[6],
		exclusive_particip = args[7],
		SMOTE=args[8], 
		ext_resp_len = args[9], 
		len_method = args[10], 
		sens_var = args[11], 
		progalt_post_or_pre =args[12],
		intra_impute=args[],
		exclusive_particip=args[],
		ext_base_effect=args[13], 
		extend_prob=args[14], 
		extend_days=args[15], 
		extend_prop=args[16], 
		topoff_rate=args[17], 
		topoff_minlength=args[18],
		bene_effect=args[19],
		dependent_allow=args[],
		full_particip_needer=args[20], 
		wait_period=args[21], 
		clone_factor=args[22], 
		week_bene_cap=args[23],
		week_bene_min=args[],
		own_uptake=args[24], 
		matdis_uptake=args[25], 
		bond_uptake=args[26], 
		illparent_uptake=args[27],
		illspouse_uptake=args[28], 
		illchild_uptake=args[29],
		maxlen_own=args[30], 
		maxlen_matdis=args[31], 
		maxlen_bond=args[32], 
		maxlen_illparent=args[33], 
		maxlen_illspouse=args[34], 
		maxlen_illchild=args[35],
		maxlen_total=args[36],
		maxlen_PFL=args[37], 
		maxlen_DI=args[38], 
		earnings=args[39], 
		own_elig_adj=args[40],
		matdis_elig_adj=args[], 
		bond_elig_adj=args[],
		illspouse_elig_adj=args[],
        illparent_elig_adj=args[],
		illchild_elig_adj=args[],
		output==args[],
		random_seed=args[])
}